global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*):10250'
      replacement: '${1}:9100'
      target_label: __address__
      action: replace
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'accessibility-api'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: accessibility-api
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      action: keep
      regex: 3000
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: pod

  - job_name: 'accessibility-cdn'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: accessibility-cdn
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      action: keep
      regex: 3000
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: pod

  - job_name: 'accessibility-frontend'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: accessibility-frontend
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      action: keep
      regex: 3000
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: pod
