apiVersion: apps/v1
kind: Deployment
metadata:
  name: accessibility-api
  labels:
    app: accessibility-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accessibility-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: accessibility-api
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/accessibility-api:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Database configuration
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: accessibility-db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: accessibility-db-credentials
              key: port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: accessibility-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accessibility-db-credentials
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: accessibility-db-credentials
              key: database
        # Redis configuration
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: accessibility-redis-credentials
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: accessibility-redis-credentials
              key: port
        # JWT secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: accessibility-jwt-secret
              key: secret
        # Other environment variables would be included here
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs-volume
          mountPath: /usr/src/app/logs
      volumes:
      - name: logs-volume
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: accessibility-api
  labels:
    app: accessibility-api
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: accessibility-api
  type: ClusterIP
